import 'package:flutter/material.dart';
import 'package:package_info_plus/package_info_plus.dart';
import '../../core/storage/local_storage.dart';
import '../../app.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key});

  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  int dailyGoal = 5;
  bool isDarkMode = false;
  double arabicFontSize = 32.0;
  String appVersion = '1.0.0';
  String playMode = 'manual';
  static const String _privacyPolicy = '''Privacy Policy - Iqra Quran Daily

Iqra Quran Daily is developed to help users read, listen to, and track their daily Quran recitation in a respectful and distraction-free environment.

Information Collection and Use

Iqra Quran Daily does not collect, store, or share any personal or sensitive user data.
The app does not require user registration, login, or account creation.

Local Data Storage

The app stores certain information locally on the user's device only to enable core features such as:

- Reading progress
- Daily goals and streak tracking
- Bookmarked verses
- App preferences (theme, font size)

This data remains on the device and is never transmitted to the developer or any third party.

Network Usage

Iqra Quran Daily may access the internet to:

- Fetch Quran text as an online fallback
- Stream Quran audio recitations

These services are provided by AlQuran Cloud API.
No personal or identifiable user information is transmitted during these requests.

Third-Party Services

The app uses the following third-party services:

- AlQuran Cloud API - Quran text and audio recitation
- Google Play Services - required for app distribution and system functionality

These services may collect limited technical information as governed by their respective privacy policies.

Log Data

In the event of an error or crash, limited technical information such as device type and operating system version may be generated by the system. This information is used solely to improve app stability and performance.

Data Security

Since Iqra Quran Daily does not collect or store personal data, there is no risk of unauthorized access, misuse, or sharing of user information.

Children's Privacy

Iqra Quran Daily does not knowingly collect any personally identifiable information from children under the age of 13. The app is suitable for users of all ages under parental guidance.

Changes to This Privacy Policy

This Privacy Policy may be updated from time to time. Any changes will be posted on this page.

Contact Us

If you have any questions or concerns regarding this Privacy Policy, please contact us at:
hafsarahman007@gmail.com.
''';
  static const String _hasanatDisclaimer =
      'Hasanat values shown in the app are estimates intended for motivation and self-tracking only. Actual reward is known only to Allah.';

  @override
  void initState() {
    super.initState();
    loadSettings();
  }

  Future<void> loadSettings() async {
    final info = await PackageInfo.fromPlatform();
    if (mounted) {
      setState(() {
        dailyGoal = LocalStorage.getDailyGoal();
        isDarkMode = LocalStorage.isDarkMode();
        arabicFontSize = LocalStorage.getArabicFontSize();
        playMode = LocalStorage.getPlayMode(); // ✅ NEW
        appVersion = info.version;
      });
    }
  }

  void updateDailyGoal(int change) {
    setState(() {
      dailyGoal = (dailyGoal + change).clamp(1, 50);
      LocalStorage.setDailyGoal(dailyGoal);
    });
  }

  void updateFontSize(double change) {
    setState(() {
      arabicFontSize = (arabicFontSize + change).clamp(20.0, 60.0);
      LocalStorage.setArabicFontSize(arabicFontSize);
    });
  }

  void showResetDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Reset Progress'),
        content: const Text(
          'Are you sure you want to reset all your progress? This action cannot be undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
                LocalStorage.resetAllReadingStats();
                Navigator.pop(context);
                ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('Progress reset')),
                );
                },
            child: const Text(
              'Reset',
              style: TextStyle(color: Colors.red),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    
    return Scaffold(
      appBar: AppBar(
        title: const Text('Settings'),
        centerTitle: true,
      ),
      body: ListView(
        padding: const EdgeInsets.all(24),
        children: [
          const SizedBox(height: 20),
          const Text(
            'Playback Mode',
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 10),

          RadioListTile<String>(
            title: const Text('Manual Reading'),
            value: 'manual',
            groupValue: playMode,
            onChanged: (value) {
              setState(() {
                playMode = value!;
                LocalStorage.setPlayMode(playMode);
              });
            },
          ),

          RadioListTile<String>(
            title: const Text('Continuous Recitation'),
            subtitle: const Text('Auto play next ayah'),
            value: 'auto',
            groupValue: playMode,
            onChanged: (value) {
              setState(() {
                playMode = value!;
                LocalStorage.setPlayMode(playMode);
              });
            },
          ),

          RadioListTile<String>(
            title: const Text('Repeat Ayah'),
            subtitle: const Text('For memorization'),
            value: 'repeat',
            groupValue: playMode,
            onChanged: (value) {
              setState(() {
                playMode = value!;
                LocalStorage.setPlayMode(playMode);
              });
            },
          ),
          Text(
            'Daily goal',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  color: Colors.grey,
                ),
          ),
          const SizedBox(height: 16),

          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
            decoration: BoxDecoration(
              color: isDark ? Colors.grey[900] : Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isDark ? Colors.grey[800]! : Colors.grey[300]!,
              ),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                  icon: const Icon(Icons.remove_circle_outline),
                  onPressed: () => updateDailyGoal(-1),
                  iconSize: 32,
                  color: Colors.teal,
                ),
                Column(
                  children: [
                    Text(
                      '$dailyGoal',
                      style: const TextStyle(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const Text(
                      'ayahs per day',
                      style: TextStyle(
                        color: Colors.grey,
                        fontSize: 14,
                      ),
                    ),
                  ],
                ),
                IconButton(
                  icon: const Icon(Icons.add_circle_outline),
                  onPressed: () => updateDailyGoal(1),
                  iconSize: 32,
                  color: Colors.teal,
                ),
              ],
            ),
          ),

          const SizedBox(height: 32),

          // Font Size
          Text(
            'Arabic font size',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  color: Colors.grey,
                ),
          ),
          const SizedBox(height: 16),

          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
            decoration: BoxDecoration(
              color: isDark ? Colors.grey[900] : Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isDark ? Colors.grey[800]! : Colors.grey[300]!,
              ),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                  icon: const Icon(Icons.text_decrease),
                  onPressed: () => updateFontSize(-2),
                  iconSize: 28,
                  color: Colors.teal,
                ),
                Column(
                  children: [
                    Text(
                      '${arabicFontSize.toInt()}',
                      style: const TextStyle(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const Text(
                      'font size',
                      style: TextStyle(
                        color: Colors.grey,
                        fontSize: 14,
                      ),
                    ),
                  ],
                ),
                IconButton(
                  icon: const Icon(Icons.text_increase),
                  onPressed: () => updateFontSize(2),
                  iconSize: 28,
                  color: Colors.teal,
                ),
              ],
            ),
          ),

          const SizedBox(height: 32),

          // Theme
          Text(
            'Theme',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  color: Colors.grey,
                ),
          ),
          const SizedBox(height: 16),

          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            decoration: BoxDecoration(
              color: isDark ? Colors.grey[900] : Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isDark ? Colors.grey[800]! : Colors.grey[300]!,
              ),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    Icon(
                      isDarkMode ? Icons.dark_mode : Icons.light_mode,
                      color: Colors.teal,
                    ),
                    const SizedBox(width: 12),
                    Text(
                      isDarkMode ? 'Dark Mode' : 'Light Mode',
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
                Switch(
                  value: isDarkMode,
                  onChanged: (value) {
                    setState(() {
                      isDarkMode = value;
                    });
                    QuranCompanionApp.of(context)?.toggleTheme();
                  },
                  activeColor: Colors.teal,
                ),
              ],
            ),
          ),

          const SizedBox(height: 32),

          // Reset Progress
          SizedBox(
            width: double.infinity,
            height: 56,
            child: OutlinedButton(
              onPressed: showResetDialog,
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Colors.red),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Text(
                'Reset progress',
                style: TextStyle(
                  fontSize: 16,
                  color: Colors.red,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ),

          const SizedBox(height: 32),

          // App info
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Center(
                child: Column(
                  children: [
                    Text(
                      'Iqra Quran Daily',
                      style: TextStyle(
                        color: Colors.grey[600],
                        fontSize: 14,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      'Version $appVersion',
                      style: TextStyle(
                        color: Colors.grey[700],
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              Text(
                _privacyPolicy,
                textAlign: TextAlign.left,
                style:
                    Theme.of(context).textTheme.bodySmall?.copyWith(height: 1.4),
              ),
              const SizedBox(height: 16),
              Text(
                _hasanatDisclaimer,
                textAlign: TextAlign.left,
                style:
                    Theme.of(context).textTheme.bodySmall?.copyWith(height: 1.4),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
